root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./.tmp/main"
  pre_cmd = ["cd ui && bun run build"]
  cmd = "go build -tags=dev -o ./.tmp/main ./cmd/main"
  post_cmd = []
  delay = 1000
  exclude_dir = ["assets", ".tmp", "vendor", "testdata", "ui/node_modules", "ui/.dist"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "js", "ts"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 100
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 3000
  enabled = true
  proxy_port = 8080

[screen]
  clear_on_rebuild = false
  keep_scroll = true
