version: "3"

services:
  redis:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - REDIS_HOST=redis:6379
    restart: always

volumes:
  redis-data: